language: java
jdk:
- openjdk11
os:
- linux
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.gradle"
before_script: 
script:
- "./gradlew clean build"
after_script: 
deploy:
  provider: heroku
  app: micronaut
  api_key:
    secure: MtC+nIOceTyy66ZkVWr3q44ItZFJAwgN6XrIFNC/U8fQzQbOPCmVmJ7OGzaSSiUrVQ1u2MB2bqsxHG4eFu+Pa56Hcrdka/ut3jImE1PR5YLdDpQ/U/jZL5Qftn49VXQjVf0JRYg2TXbxY4pp8KU6XWPQDhx31pf+4/zpws7rEgnS00pRG/PhN547u3eJp3se7S8LnUFQubvG9wEeKIR1WcKJQBO5dIUXDiy2P43URjAHdd4OKVTs62AzMGpIn35TKZFwH6XehqaTVG6Cxa5XeuyjRUhKomZkKElz69SlfZD9XJK6IT865Pu2pdnScaIsRzeapXrCu375saXECmEZOaQ+pHmgI5KpU7qEDR94zdx67GHyyb4wsUQt/IuMC9mGFzMcEcIjypvTcRrCPCG36G6f3mcV2U5W5IH0y6fi34/TmJqLpJialIg2m8NBPYSC9DPmYfSNjYsYYXvoKp7o0/ADsDBdjH2PU6me+DJifYw81butRhqQ64Q39SNsd/B77I323UyHtsUkI0w2+tQKRhgSsm2IpbFKTUMN2aGdmVRl5ZCMpzXHR9agl7eDxev+zXvHVB8H11df+dytVZWcF/G+2PTcczCKcz5UOQ99NdxPwFeZxuYAWAIxirrGg9w1YDQei//ITrPf6fctaOf/t4X/tcrYTec+jZ+m6yZvaEo=
