micronaut:
  application:
    name: micronaut
endpoints:
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
myapp:
  endpoint: ${myapp.mystuff:`default-v`}
