micronaut:
  application:
    name: micronaut
endpoints:
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
twilio:
  account-sid: ${twilio.account.sid:`secret-default`}
  auth-token: ${twilio.auth.token:`secret-default`}
  path: ${twilio.path:`secret-default`}
  number: ${twilio.number:`secret-default`}
myauth:
  sender: ${auth.sender:}
honey:
  key: ${HONEYCOMB_KEY}


datasources:
  default:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
