micronaut:
  application:
    name: micronaut
  server:
    port: ${PORT}
endpoints:
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
redis:
  url: ${REDIS_URL}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
