micronaut:
  application:
    name: micronaut
  server:
    port: ${PORT}
endpoints:
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
