micronaut:
  application:
    name: micronaut
endpoints:
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
twilio:
  account-sid: ${twilio.account.sid:`secret-default`}
  auth-token: ${twilio.auth.token:`secret-default`}
