micronaut:
  application:
    name: micronaut
endpoints:
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
twilio:
  account-sid: ${twilio.account.sid:`secret-default`}
  auth-token: ${twilio.auth.token:`secret-default`}
  path: ${twilio.path:`secret-default`}
  number: ${twilio.number:`secret-default`}
myauth:
  sender: ${auth.sender:}


datasources:
  default:
    url: ${JDBC_DATABASE_URL:`jdbc:h2:mem:devDb`}
    driverClassName: ${bank.db.driver:`org.h2.Driver`}
    username: ${JDBC_DATABASE_USERNAME:`sa`}
    password: ${JDBC_DATABASE_PASSWORD:`''`}
