micronaut:
  application:
    name: micronaut
endpoints:
  info:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
twilio:
  account-sid: ${twilio.account.sid:`secret-default`}
  auth-token: ${twilio.auth.token:`secret-default`}
  path: ${twilio.path:`secret-default`}
  number: ${twilio.number:`secret-default`}
myauth:
  sender: ${auth.sender:}

datasources:
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'docker'
    dialect: postgres
  app:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'docker'
    dialect: postgres
